version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: accessmed-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accessmed

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:

    build: .

    container_name: accessmed-api

    depends_on:
      - postgres

    ports:
      - "5000:5000"

    env_file:
      - .env

volumes:

  postgres_data: